version : '3'

services:
    lb:
        image: haproxy
        ports:
            - "8080:8080"
        volumes:
            - ./haproxy:/usr/local/etc/haproxy
    nodeapp:
        image: nodeapp
        environment:
            - APPID=2222
    courseapp:
        image: courseapp
        environment:
            - APPID=1111