version : '3'

services:
    lb:
        image: haproxy
        ports:
            - "80:80"
        volumes:
            - ./haproxy:/usr/local/etc/haproxy
    userapp:
        image: userapp
        build:
            context: ./user-app/
            dockerfile: Dockerfile.userapp
        environment:
            - APPID=2222
    courseapp:
        image: courseapp
        build:
            context: ./course-app/
            dockerfile: Dockerfile.courseapp
        environment:
            - APPID=1111